spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs